name: Build RedisGraph Shared Library (.so)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ make libxxhash-dev libgraphblas-dev

      - name: Set environment variables
        run: |
          echo "CMAKE_CC_FLAGS=-O2 -g" >> $GITHUB_ENV
          echo "CMAKE_LD_FLAGS=-L/usr/local/lib" >> $GITHUB_ENV
          echo "CMAKE_SO_LD_FLAGS=-shared" >> $GITHUB_ENV
          echo "GRAPHBLAS=1" >> $GITHUB_ENV
          echo "LIBXXHASH=1" >> $GITHUB_ENV
          echo "LIBCYPHER_PARSER=1" >> $GITHUB_ENV
          echo "REDISEARCH_LIBS=1" >> $GITHUB_ENV
          echo "UTF8PROC=1" >> $GITHUB_ENV
          echo "ONIGURUMA=1" >> $GITHUB_ENV

      - name: List current directory contents
        run: ls -al

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake
        run: |
          cd build
          cmake ..

      - name: Build RedisGraph
        run: |
          cd build
          make

      - name: Check for redisgraph.so
        run: |
          ls -l src/redisgraph.so

      - name: Upload redisgraph.so
        uses: actions/upload-artifact@v3
        with:
          name: redisgraph-so
          path: src/redisgraph.so
