name: Build RedisGraph Shared Library (.so)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 初始化子模块
      - name: Initialize submodules
        run: git submodule update --init --recursive

      # 安装依赖项
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc g++ make libgraphblas-dev libxxhash-dev \
                                  libcypher-parser-dev libutf8proc-dev oniguruma-dev \
                                  libjemalloc-dev
      
      # 设置环境变量（根据实际需要设置）
      - name: Set environment variables
        run: |
          export CMAKE_CC_FLAGS="-O3"
          export CMAKE_LD_FLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro"
          export GRAPHBLAS="/usr/include/graphblas"
          export LIBXXHASH="/usr/include/xxhash"
          export RAX="/usr/include/rax"
          export LIBCYPHER_PARSER="/usr/include/cypher-parser"
          export REDISEARCH_LIBS="/usr/lib/redisearch"
          export UTF8PROC="/usr/include/utf8proc"
          export ONIGURUMA="/usr/include/oniguruma"
        shell: bash

      # 创建构建目录
      - name: Create build directory
        run: mkdir -p build

      # 运行 CMake 配置
      - name: Run CMake
        run: |
          cd build
          cmake ..

      # 编译并生成 redisgraph.so 文件
      - name: Build RedisGraph
        run: |
          cd build
          make

      # 验证生成的 redisgraph.so 文件
      - name: Check for redisgraph.so
        run: |
          ls -l src/redisgraph.so

      # 保存生成的 .so 文件为构建工件
      - name: Upload redisgraph.so
        uses: actions/upload-artifact@v3
        with:
          name: redisgraph-so
          path: src/redisgraph.so